# coding: utf-8
"""
    Forge Keeper - Conductor

    This API focuses on managing data archives and drones that submit data to them.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: not@vailable
    Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

import unittest

from digital.forge.data.models.drone_inputs import DroneInputs


class TestDroneInputs(unittest.TestCase):
    """DroneInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    @staticmethod
    def make_instance():
        """Returns an instance with example values as defined in the API."""
        return DroneInputs(
            name='Server room',
            description='Monitors temperature in the server room.'
        )

    def test_drone_inputs(self):
        """Test DroneInputs"""
        instance = TestDroneInputs.make_instance()
        self.assertEqual('Server room', instance.name)
        self.assertEqual(
            'Monitors temperature in the server room.',
            instance.description
        )

    def test_name(self):
        """Test the "name" property"""
        instance = TestDroneInputs.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='name cannot be set to null'
        ):
            instance.name = None

        # Check some valid values.
        valid_values = [
            'Thorin',
            'Bifur',
            'Bofur',
            'Bombur',
        ]
        for value in valid_values:
            instance.name = value
            self.assertEqual(
                value,
                instance.name,
                msg='name can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            789,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='name cannot be set to an invalid value'
            ):
                instance.name = value

    def test_description(self):
        """Test the "description" property"""
        instance = TestDroneInputs.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='description cannot be set to null'
        ):
            instance.description = None

        # Check some valid values.
        valid_values = [
            'Chip the glasses and crack the plates!',
            'Blunt the knives and bend the forks!',
            'That\'s what Bilbo Baggins hates',
            'Smash the bottles and burn the corks!',
        ]
        for value in valid_values:
            instance.description = value
            self.assertEqual(
                value,
                instance.description,
                msg='description can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            3535,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='description cannot be set to an invalid value'
            ):
                instance.description = value

    def test_equals(self):
        """Test equality operations"""
        obj_a = TestDroneInputs.make_instance()
        obj_b = TestDroneInputs.make_instance()
        obj_c = TestDroneInputs.make_instance()

        # Create a different object.
        obj_x = TestDroneInputs.make_instance()
        obj_x.name = 'mendicant bias'

        self.assertEqual(obj_a, obj_a, msg='Reflexive property: a == a')
        self.assertEqual(obj_a, obj_b, msg='Symmetric property: a == b')
        self.assertEqual(obj_b, obj_a, msg='Symmetric property: b == a')
        self.assertEqual(obj_b, obj_c, msg='Transitive property: b == c')
        self.assertEqual(obj_a, obj_c, msg='Transitive property: a == c')

        self.assertNotEqual(obj_a, obj_x, msg='Not equals: a != x')

        self.assertNotEqual(obj_a, 'foobar', msg='The object is not a string')
        self.assertNotEqual(obj_a, None, msg='The object is not null')


if __name__ == '__main__':
    unittest.main()
