# coding: utf-8
"""
    Forge Keeper - Conductor

    This API focuses on managing data archives and drones that submit data to them.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: not@vailable
    Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

from datetime import datetime
import unittest

from digital.forge.data.models.archive import Archive


class TestArchive(unittest.TestCase):
    """Archive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    @staticmethod
    def make_instance():
        """Returns an instance with example values as defined in the API."""
        return Archive(
            uuid='7b9aed83-ed5a-47bf-a02a-8530369d545c',
            name='temperature',
            description='An archive of historical temperature data.',
            data_type='float',
            units='C',
            creation_time='2020-07-25T17:32:28Z'
        )

    def test_archive(self):
        """Test Archive"""
        instance = TestArchive.make_instance()
        self.assertEqual('7b9aed83-ed5a-47bf-a02a-8530369d545c', instance.uuid)
        self.assertEqual('temperature', instance.name)
        self.assertEqual(
            'An archive of historical temperature data.',
            instance.description
        )
        self.assertEqual('float', instance.data_type)
        self.assertEqual('C', instance.units)
        self.assertEqual('2020-07-25T17:32:28Z', instance.creation_time)

    def test_uuid(self):
        """Test the "uuid" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='uuid cannot be set to null'
        ):
            instance.uuid = None

        # Check some valid values.
        valid_values = [
            '7b9aed83-ed5a-47bf-a02a-8530369d545c',
            'e3599955-f0bf-4853-90e3-4a93015f96c0',
        ]
        for value in valid_values:
            instance.uuid = value
            self.assertEqual(
                value,
                instance.uuid,
                msg='uuid can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            1234,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='uuid cannot be set to an invalid value'
            ):
                instance.uuid = value

    def test_name(self):
        """Test the "name" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='name cannot be set to null'
        ):
            instance.name = None

        # Check some valid values.
        valid_values = [
            'James',
            'Alex',
            'Naomi',
            'Amos',
            'TK-421',
        ]
        for value in valid_values:
            instance.name = value
            self.assertEqual(
                value,
                instance.name,
                msg='name can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            1234,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='name cannot be set to an invalid value'
            ):
                instance.name = value

    def test_description(self):
        """Test the "description" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='description cannot be set to null'
        ):
            instance.description = None

        # Check some valid values.
        valid_values = [
            'Hey you!',
            '',
            'You\'re finally awake!',
        ]
        for value in valid_values:
            instance.description = value
            self.assertEqual(
                value,
                instance.description,
                msg='description can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            -1,
            1337,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='description cannot be set to an invalid value'
            ):
                instance.description = value

    def test_data_type(self):
        """Test the "data_type" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='data_type cannot be set to null'
        ):
            instance.data_type = None

        # Check some valid values.
        valid_values = [
            'float',
            'string',
            'double',
            'integer',
        ]
        for value in valid_values:
            instance.data_type = value
            self.assertEqual(
                value,
                instance.data_type,
                msg='data_type can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            0,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='data_type cannot be set to an invalid value'
            ):
                instance.data_type = value

    def test_units(self):
        """Test the "units" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='units cannot be set to null'
        ):
            instance.units = None

        # Check some valid values.
        valid_values = [
            'K',
            'Kelvin',
            'moles',
        ]
        for value in valid_values:
            instance.units = value
            self.assertEqual(
                value,
                instance.units,
                msg='units can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            501,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='units cannot be set to an invalid value'
            ):
                instance.units = value

    def test_creation_time(self):
        """Test the "creation_time" property"""
        instance = TestArchive.make_instance()

        # This value can't be set to null.
        with self.assertRaises(
                ValueError,
                msg='creation_time cannot be set to null'
        ):
            instance.creation_time = None

        # Check some valid values.
        valid_values = [
            datetime(2063, 4, 5),
            datetime(2157, 1, 1, 12, 34, 56),
        ]
        for value in valid_values:
            instance.creation_time = value
            self.assertEqual(
                value,
                instance.creation_time,
                msg='creation_time can be set to valid value "%r"' % (value)
            )

        # Check some invalid values raise ValueError exceptions.
        invalid_values = [
            'first contact',
            1234,
            [],
            {},
        ]
        for value in invalid_values:
            with self.assertRaises(
                    ValueError,
                    msg='creation_time cannot be set to an invalid value'
            ):
                instance.creation_time = value

    def test_equals(self):
        """Test equality operations"""
        obj_a = TestArchive.make_instance()
        obj_b = TestArchive.make_instance()
        obj_c = TestArchive.make_instance()

        # Create a different object.
        obj_x = TestArchive.make_instance()
        obj_x.name = 'Q'

        self.assertEqual(obj_a, obj_a, msg='Reflexive property: a == a')
        self.assertEqual(obj_a, obj_b, msg='Symmetric property: a == b')
        self.assertEqual(obj_b, obj_a, msg='Symmetric property: b == a')
        self.assertEqual(obj_b, obj_c, msg='Transitive property: b == c')
        self.assertEqual(obj_a, obj_c, msg='Transitive property: a == c')

        self.assertNotEqual(obj_a, obj_x, msg='Not equals: a != x')

        self.assertNotEqual(obj_a, 'foobar', msg='The object is not a string')
        self.assertNotEqual(obj_a, None, msg='The object is not null')


if __name__ == '__main__':
    unittest.main()
