# coding: utf-8
"""
This module includes utilities for type checking.

Note: This file is compatible only with Python 3.7+

This file is automatically generated! **DO NOT TOUCH!**
"""


def is_generic(klass):
    """ Determine whether klass is a generic class """
    return hasattr(klass, '__origin__')


def is_dict(klass):
    """ Determine whether klass is a Dict """
    return klass.__origin__ == dict


def is_list(klass):
    """ Determine whether klass is a List """
    return klass.__origin__ == list
