version: '3.7'

services:

    drone:
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        image: forge-drone
        secrets:
            - source: conf
              target: /etc/py-drone.conf
            - source: https-cert
              target: /etc/ssl/certs/cert.pem

secrets:
    conf:
        #external: true
        #name: forge-drone-conf
        file: /etc/py-drone.conf
    https-cert:
        #external: true
        #name: forge-keeper-https-cert
        file: /etc/ssl/certs/cert.pem
