version: '3.7'

services:

    web:
        image: forge-keeper
        command: -h 0.0.0.0 -p 80
        build:
            context: .
        restart: always
        ports:
            - target: 80
              published: 50080
              protocol: tcp
        secrets:
            - psql-host
            - psql-port
            - psql-name
            - psql-conductor-user
            - psql-conductor-pass

secrets:
    psql-host:
        external: true
        name: forge-keeper-psql-host
    psql-port:
        external: true
        name: forge-keeper-psql-port
    psql-name:
        external: true
        name: forge-keeper-psql-name
    psql-conductor-user:
        external: true
        name: forge-keeper-psql-conductor-user
    psql-conductor-pass:
        external: true
        name: forge-keeper-psql-conductor-pass
